# Generated by Django 4.2.1 on 2023-05-27 11:56

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(default=game.models.generate_room_id, null=True)),
                ('players_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rooms_id', models.CharField(default=None, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('total_hp', models.IntegerField(default=100)),
                ('remain_hp', models.IntegerField(default=100)),
                ('action', models.CharField(default=None, null=True)),
                ('has_armor', models.BooleanField(default=False)),
                ('state', models.CharField(default='wait')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.rooms')),
            ],
        ),
    ]
