# Generated by Django 4.2.1 on 2023-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='a98833fb296a4717b94f4a7ef8afad99', null=True),
        ),
    ]
