# Generated by Django 4.2.1 on 2023-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_rooms_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='eda4d94b2d944a61be865185c6afcf4d', null=True),
        ),
    ]
